[project]
name = "robs-pygame-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.11.0",
    "noise>=1.2.2",
    "numpy==2.4.6",
    "opensimplex>=0.4.5.1",
    "pygame-ce==2.5.7",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "scipy-stubs~=1.17.1",
]
